### ISSUE TITLE
STM32_gen_peripheralPins.py chrashing after generating pinmaps

### ISSUE THREAD

**Issue by lefebvresam** [mbed-ce/mbed-os#212] opened 2024-01-18 16:36 UTC
### Description of defect

When generating pinmap files the script is crashing:

```
mbed-os$ python targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py -m "STM32U575RGTx.xml"

Script version 1.20.5

Checking STM32_open_pin_data repo...
        Already up to date.

STM32_open_pin_data DB version STM32CubeMX-DB.6.0.90

 * Output directory: /home/samlef/git/hmipanel/mbed-os/TARGET_CUSTOM/TARGET_STM/TARGET_STM32U5/TARGET_STM32U575xG/TARGET_STM32U575RGT
 * Generating PeripheralPins.c and PinNames.h with 'STM32_open_pin_data/mcu/STM32U575RGTx.xml'
 * GPIO file: STM32_open_pin_data/mcu/IP/GPIO-STM32U5x_gpio_v1_0_Modes.xml
Traceback (most recent call last):
  File "targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py", line 1933, in <module>
    parse_pins()
  File "targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py", line 1399, in parse_pins
    if "Variant" in s.attributes:
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 522, in __getitem__
    return self._attrs[attname_or_tuple]
KeyError: 0
```

#### Target(s) affected by this defect ?

Custom target

#### Toolchain(s) (name and version) displaying this defect ?

NA

#### What version of Mbed-os are you using (tag or sha) ?

Mbed 7.59.0

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)

CLI2

#### How is this defect reproduced ? 

Execute command above

**Comment by lefebvresam** [comment] 2024-01-18 17:15
I could use it succesfully on another Linux laptop.

**Comment by JohnK1987** [comment] 2024-01-18 18:38
Can not be this caused by python version?
I tried that on my windows 10 machine and seems to be OK.
```
D:\Mbed\MbedCE\MbedCE_STM32H5xxxx\mbed-os\targets\TARGET_STM\tools>STM32_gen_PeripheralPins.py -m "STM32U575RGTx.xml"

Script version 1.20.5

Checking STM32_open_pin_data repo...
*** git clone https://github.com/STMicroelectronics/STM32_open_pin_data.git ***
*** git clone done

STM32_open_pin_data DB version STM32CubeMX-DB.6.0.90

 * Output directory: D:\Mbed\MbedCE\MbedCE_STM32H5xxxx\mbed-os\targets\TARGET_STM\tools\TARGET_CUSTOM\TARGET_STM\TARGET_STM32U5\TARGET_STM32U575xG\TARGET_STM32U575RGT
 * Generating PeripheralPins.c and PinNames.h with 'STM32_open_pin_data\mcu\STM32U575RGTx.xml'
 * GPIO file: STM32_open_pin_data\mcu\IP\GPIO-STM32U5x_gpio_v1_0_Modes.xml
 * I/O pins found: 120 connected: 1


D:\Mbed\MbedCE\MbedCE_STM32H5xxxx\mbed-os\targets\TARGET_STM\tools>
```

**Comment by lefebvresam** [comment] 2024-01-18 19:30
Difficult to reproduce, because it was one in WSL2 on a Windows bootcamp, but after a fatal crash with a non bootcamp supported tool in Windows I had to reinstall my whole partition and lost half of a week and a lot of docs on my desktop. But however, maybe it's an idea to catch that error in the code and create a message for it.

**Comment by multiplemonomials** [comment] 2024-01-19 06:12
I think I'd like to close this one for now unless we can find a way to reproduce the issue.  Any objections?

**Comment by JohnK1987** [comment] 2024-01-19 06:18
`"/usr/lib/python2.7/xml/dom/minidom.py"`
I believe it is caused by using python 2.7 instead of 3+

**Comment by multiplemonomials** [comment] 2024-01-19 06:35
ah yeah, that will do it

**Comment by lefebvresam** [comment] 2024-01-19 08:11
Maybe in the script doing a verifiaction for Python version before continuing?

**Comment by multiplemonomials** [comment] 2024-01-19 08:39
Could you make a PR for that?

**Comment by lefebvresam** [comment] 2024-01-19 09:05
Let me first bringup my new environment.

**Comment by JohnK1987** [comment] 2024-01-19 09:19
So we can add something like this at the beginning of the script maybe?

```
import sys
if sys.version_info[0] < 3:
    raise Exception("Must be using Python 3")
```

I can test it and make the PR later. You can focus other things.

**Comment by JohnK1987** [comment] 2024-01-19 21:20
Ok, we have an info about Python version requirement directly in the .py script now.

**Closed by JohnK1987** 2024-01-19 21:20 UTC
